---

- name: Create production group
  group:
    name: "{{ PRODUCTION_GROUP }}"

- name: Create production user
  user:
    name: "{{ PRODUCTION_USER }}"
    comment: "webapp user"
    shell: /bin/nologin
    group: "{{ PRODUCTION_GROUP }}"

- name: Create project directory
  file:
    path: "{{ PROJECT_DIRECTORY }}"
    state: directory
    owner: "{{ PRODUCTION_USER }}"
    group: "{{ PRODUCTION_GROUP }}"
    mode: "0775"

- name: Install binary
  copy:
    src: "{{ BIN_SOURCE_PATH }}"
    dest: "{{ PROJECT_DIRECTORY }}"
    owner: "{{ PRODUCTION_USER }}"
    group: "{{ PRODUCTION_GROUP }}"
    mode: "0775"

- name: Render and install systemd unit
  template:
    src: templates/systemd-service.j2
    dest: /etc/systemd/system/helloWeb.service
    owner: root
    group: root
    mode: "0644"

- name: Enable project service
  service:
    name: helloWeb
    state: started
    enabled: yes
    daemon_reload: yes
